Feedback when switching versions

diff --git a/switch-phpunit-version b/switch-phpunit-version
--- a/switch-phpunit-version
+++ b/switch-phpunit-version
@@ -1,4 +1,6 @@
 #!/bin/bash
+set -e
+
 if [ "$1" = "latest" ]
 then
 	version=9
@@ -6,5 +8,14 @@ else
 	version=$1
 fi
 
-rm -f /usr/local/bin/phpunit
-ln -s "/usr/local/bin/phpunit-$version" "/usr/local/bin/phpunit"
+phpunit_bin="/usr/local/bin/phpunit-$version"
+
+if test -f $phpunit_bin
+then
+	rm -f /usr/local/bin/phpunit
+	ln -s "$phpunit_bin" "/usr/local/bin/phpunit"
+	echo "Successfully linked $phpunit_bin"
+else
+	echo "Error linking $phpunit_bin: version doesn't exit"
+	exit 1
+fi
